# REAL MADRID INTERNSHIP TEST NOTEBOOK

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("data_acute_vs_chronic.csv")

In [3]:
df.head()

,player_id,period_id,period_name,activity_id,period_start_time,position_name_en,is_official_match,total_distance,acc_band7plus_total_effort_count,velocity_band6plus7_total_distance,height,weight,date_of_birth
0,37191,period_1683,BP 2351,activity_1389,2024-12-16T00:00:00Z,Central Back,NaN,1003.372036,0,0.000000,184.0,79.0,1997-06-22
1,37191,period_4407,G 1669,activity_2423,2025-01-01T00:00:00Z,Central Back,NaN,1223.749101,4,4.960388,184.0,79.0,1997-06-22
2,37191,period_883,BP 4893,activity_4655,2025-04-06T00:00:00Z,Central Back,NaN,747.250469,4,0.000000,184.0,79.0,1997-06-22
3,37191,period_1790,G 3164,activity_911,2025-04-03T00:00:00Z,Central Back,NaN,1196.351675,2,0.000000,184.0,79.0,1997-06-22
4,37191,period_2421,BP 0518,activity_3073,2025-05-06T00:00:00Z,Central Back,NaN,322.200458,2,0.000000,184.0,79.0,1997-06-22

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 13 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   player_id                           3903 non-null   int64
 1   period_id                           3903 non-null   object
 2   period_name                         2930 non-null   object
 3   activity_id                         3903 non-null   object
 4   period_start_time                   3903 non-null   object
 5   position_name_en                    3884 non-null   object
 6   is_official_match                   973 non-null    float64
 7   total_distance                      3903 non-null   float64
 8   acc_band7plus_total_effort_count    3903 non-null   int64
 9   velocity_band6plus7_total_distance  3903 non-null   float64
 10  height                              3884 non-null   float64
 11  weight                              3884 non-null   float64
 12  date_of_birth                       3884 non-null   object
dtypes: float64(5), int64(2), object(6)
memory usage: 396.5+ KB

In [8]:
df.describe()

,player_id,is_official_match,total_distance,acc_band7plus_total_effort_count,velocity_band6plus7_total_distance,height,weight
count,3903.000000,973.0,3903.000000,3903.000000,3903.000000,3884.000000,3884.000000
mean,52016.641558,1.0,1335.858169,4.973098,13.356361,176.972451,75.903193
std,28098.171686,0.0,1042.696531,3.769709,20.707415,5.486529,19.355849
min,11983.000000,1.0,44.093973,0.000000,0.000000,169.000000,64.000000
25%,28635.000000,1.0,713.578274,2.000000,0.000000,173.000000,67.000000
50%,48463.000000,1.0,1170.471234,5.000000,1.281572,177.000000,71.000000
75%,70334.000000,1.0,1676.564775,7.000000,20.958936,181.000000,79.000000
max,95293.000000,1.0,32299.892493,27.000000,191.200596,195.000000,200.000000